# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Refractored.TinyClips
PackageVersion: 1.8.2.0
MinimumOSVersion: 10.0.22000.0
InstallerType: msix
InstallModes:
- silent
- silentWithProgress
PackageFamilyName: Refractored.TinyClips_vmshqmcyy894t
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jamesmontemagno/tiny-clips/releases/download/v1.8.2-windows/TinyClips-1.8.2-x64.msix
  InstallerSha256: bbec5fd75360b0f729a391f1172189c3f90ebab8d33198e1a01149b1a7d7734b
  SignatureSha256: 9c121f71d4a6a3703cb94c576073fc1ee32d5b1d1a39206cef2e576e9ec03b46
- Architecture: arm64
  InstallerUrl: https://github.com/jamesmontemagno/tiny-clips/releases/download/v1.8.2-windows/TinyClips-1.8.2-arm64.msix
  InstallerSha256: 8a1f9818988415457c94c286273b53448dc79ef732fd2b7753b991a2cec4be1d
  SignatureSha256: 58419077f732dee590db402897a375aaadc97ca3c49e2e093d554ecba26a9dc5
ManifestType: installer
ManifestVersion: 1.12.0
